<?php

function schedule_menu() {
  
  $items = array();
  
  $items['schedule/courses'] = array(
    'title' => 'Schedule',
    'description' => 'A dashboard for staff',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('schedule_form'), //put the name of the form here
    'access arguments' => array("access contents"),
  );
 
  return $items;
  
}

function createScheduleForm($form, &$form_state) {
  // Get all the course name for the current user
  $course_name = $form['currentCourse'];
    
  $form['course'] = array(
    '#type' => 'item',
    '#title' => $form['currentCourse'],
    '#options' => $course_name,
  );
    
    $format = 'Y-m-d H:i';
    $timezone= drupal_get_user_timezone();
    $form['start_date'] = array(
        '#type' => 'date_popup',
        '#title' => t('Start Time'),
        '#default_value' => date("Y-m-d H:i", round(strtotime("now") / 900) * 900),
        '#date_format' => "H:i",
        '#date_label_position' => 'within',
        '#date_timezone' => $timezone,
        '#required' => TRUE,
        '#date_increment' => 15,
        '#date_year_range' => '-3:+3',
        '#timepicker' => 'timepicker',
        '#timepicker_options' => array(
          'rows' => 6,
          'minutes' => array(
            'starts' => 0,
            'ends' => 56,
            'interval' => 4,
          ),
          'showCloseButton' => TRUE,
          'closeButtonText' => t('Close'),
        ),
      
    );
    
  $form['end_date'] = array(
    '#type' => 'date_popup',
    '#title' => t('End Time'),
    '#default_value' => date("Y-m-d H:i", round(strtotime("+1 hour") / 900) * 900),
    '#date_format' => "H:i",
    '#date_label_position' => 'within',
    '#date_timezone' => $timezone,
    '#required' => TRUE,
    '#date_increment' => 15,
    '#date_year_range' => '-3:+3',
    '#timepicker' => 'timepicker',
    '#timepicker_options' => array(
      'rows' => 6,
      'minutes' => array(
        'starts' => 0,
        'ends' => 56,
        'interval' => 4,
      ),
      'showCloseButton' => TRUE,
      'closeButtonText' => t('Close'),
      ),
      
    );
  

$form['actions']['submit'] = array(
	  
    '#type' => 'submit',
      
    '#value' => t('Schedule Class'),
      
  );
	  
	return $form;
}

function schedule_form($form, &$form_state) {
  
	$form = createScheduleForm($form, $form_state);

  return $form;

}

function schedule_form_reset($form, &$form_state) {
  
  $form_state['rebuild'] = FALSE;
  
}

function schedule_form_submit($form, &$form_state) {
	
	 // Generate the new link using the submitted text value.
  $link = _staff_dashboard_make_link($form_state['values']['new_link_text']);

  // Tell the browser to close the modal.
  $form_state['ajax_commands'][] = ctools_modal_command_dismiss();

  // Tell the browser to replace the old link with the new one.
  $form_state['ajax_commands'][] = ajax_command_replace('#magical-modal-link', $link);
  
}

?>