<?php


function custom_views_pre_render(&$view) {
    //dpm($view);
    //shuffle($view->result);
}

function custom_form_alter(&$form, &$form_state, $form_id) {
    //If clause for the submit_room_request form
    if ($form_id=="submit_room_request_node_form"){
        $form['title']['#type'] = 'hidden';
        $form['title']['#value'] = "Room Request";
        $form['actions']['submit']['#value'] = 'Request Room';
    }    
    
    if ($form_id=="search_node_form"){
        $form['title']['#type'] = 'hidden';
        //Changes save buttom name to search
        $form['actions']['submit']['#value'] = 'Search rooms';  
    
   
      $result = db_select(' taxonomy_term_data', 'ttd')
    ->fields('ttd')
//    ->condition('nid', $node->nid,'=')
//    ->condition('status', 0,'>')
//    ->condition('uid', array(1,5,7),'IN')
    ->execute()
    ->fetchAll();
    //dpm ($result);
  
    
    
      
  }
  else {
      //drupal_set_message(t('This is a different page.'), 'error');
  }
}


function custom_form_submit($form, &$form_state) {
     if ($form_id=="submit_room_request_node_form"){
         
     }
}
